openapi: 3.1.0
x-stoplight:
  id: xml3nym1ay967
info:
  title: grade_bulks
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /grade_bulks/:
    parameters: []
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    grade_items:
                      - bulk_number: 0
                        name: ''
                        sections:
                          - ''
                        stages:
                          - ''
                        levels:
                          - ''
                        courses:
                          - ''
                        course_groups:
                          - ''
                        created_by: ''
                        created_at: ''
                    meta:
                      current_page: 0
                      next_page: 0
                      prev_page: 0
                      total_count: 0
                      total_pages: 0
                properties:
                  grade_items:
                    type: array
                    items:
                      type: object
                      properties:
                        bulk_number:
                          type: integer
                        name:
                          type: string
                        sections:
                          type: array
                          items:
                            type: string
                        stages:
                          type: array
                          items:
                            type: string
                        levels:
                          type: array
                          items:
                            type: string
                        courses:
                          type: array
                          items:
                            type: string
                        course_groups:
                          type: array
                          items:
                            type: string
                        created_by:
                          type: string
                        created_at:
                          type: string
                          format: date-time
                      required:
                        - bulk_number
                        - name
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                      next_page:
                        type: integer
                      prev_page:
                        type: integer
                      total_count:
                        type: integer
                      total_pages:
                        type: integer
                required:
                  - grade_items
                  - meta
              examples:
                Example 1:
                  value:
                    grade_items:
                      - bulk_number: 5
                        name: Q1 - Math Homework
                        sections:
                          - Grade 3A
                          - Grade 3B
                        stages:
                          - Stage 1
                        levels:
                          - Primary
                        courses:
                          - Math
                        course_groups:
                          - Group 2
                        created_by: Admin User
                        created_at: '2025-10-22T12:00:00Z'
                      - bulk_number: 6
                        name: Q1 - Science Quiz
                        sections:
                          - Grade 4A
                        stages:
                          - Stage 2
                        levels:
                          - Primary
                        courses:
                          - Science
                        course_groups:
                          - Group 1
                        created_by: SuperAdmin
                        created_at: '2025-10-22T13:00:00Z'
                    meta:
                      current_page: 1
                      next_page: 2
                      prev_page: null
                      total_count: 20
                      total_pages: 2
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../../Data/UnauthorizedError.yaml
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: ../../Data/ForbiddenError.yaml
                x-examples:
                  Example 1:
                    error: Access Denied
                    message: Only Admins and SuperAdmins can access grade bulks
      operationId: ''
      description: Retrieve grouped grade items created through the Control Page (Grade Items module).
      parameters:
        - schema:
            type: integer
          in: query
          name: page
          description: Current page number
        - schema:
            type: integer
          in: query
          name: per_page
          description: Items per page
        - schema:
            type: string
          in: query
          name: sort_by
          description: Column name for sorting
        - schema:
            type: string
          in: query
          name: sort_direction
          description: Sorting order (asc / desc)
        - schema:
            type: integer
          in: query
          name: 'q[section_id]'
          description: Filter by Section ID
        - schema:
            type: string
          in: query
          name: 'q[stage_id]'
          description: Filter by Stage ID
        - schema:
            type: string
          in: query
          name: 'q[level_id]'
          description: Filter by Level ID
        - schema:
            type: string
          in: query
          description: Filter by Course ID
          name: 'q[course_id]'
        - schema:
            type: string
          in: query
          description: Filter by Course Group ID
          name: 'q[course_group_id]'
        - schema:
            type: string
          in: query
          name: 'q[grading_period]'
          description: Filter by Grading Period
        - schema:
            type: string
          in: query
          description: Filter by Category ID
          name: 'q[category_id]'
  /grade_bulks/delete_all:
    post:
      summary: ''
      operationId: ''
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    message: Grade bulks deleted successfully
                    deleted_bulk_numbers:
                      - 5
                      - 6
                      - 7
                properties:
                  message:
                    type: string
                  deleted_bulk_numbers:
                    type: array
                    x-stoplight:
                      id: ts2ovhdjg98kr
                    items:
                      x-stoplight:
                        id: ant0kztqnzqix
                      type: integer
              examples:
                '': {}
                Example 1:
                  value:
                    message: Grade bulks deleted successfully
                    deleted_bulk_numbers:
                      - 5
                      - 6
                      - 7
            application/xml:
              schema:
                type: object
                properties: {}
            multipart/form-data:
              schema:
                type: object
                properties: {}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../../Data/UnauthorizedError.yaml
        '403':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../../Data/ForbiddenError.yaml
                x-examples:
                  Example 1:
                    error: Access Denied
                    message: Only Admins and SuperAdmins can delete grade bulks
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../../Data/NotFoundError.yaml
                x-examples:
                  Example 1:
                    error: Not Found
                    message: Bulk number 7 does not exist or has been deleted
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                Example 1:
                  - 5
                  - 6
                  - 7
              properties:
                deleted_bulk:
                  type: array
                  x-stoplight:
                    id: cbf01lbb6mkah
                  items:
                    x-stoplight:
                      id: ssdnw1ur62698
                    type: integer
        description: ''
      description: 'Soft delete grouped grade items based on bulk_number values. '
    parameters: []
  /grading_periods/course_grading_periods_with_categories:
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    grading_periods:
                      - id: 0
                        name: ''
                        sub_grading_periods:
                          - id: 0
                            name: ''
                            categories:
                              - id: 0
                                name: ''
                                sub_categories:
                                  - id: 0
                                    name: ''
                        categories:
                          - id: 0
                            name: ''
                            sub_categories:
                              - id: 0
                                name: ''
                properties:
                  grading_periods:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        sub_grading_periods:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                              name:
                                type: string
                              categories:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    id:
                                      type: integer
                                    name:
                                      type: string
                                    sub_categories:
                                      type: array
                                      items:
                                        type: object
                                        properties:
                                          id:
                                            type: integer
                                          name:
                                            type: string
                        categories:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                              name:
                                type: string
                              sub_categories:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    id:
                                      type: integer
                                    name:
                                      type: string
                      required:
                        - id
                        - name
                required:
                  - grading_periods
              examples:
                Example 1:
                  value:
                    grading_periods:
                      - id: 1
                        name: Semester 1
                        sub_grading_periods:
                          - id: 11
                            name: Quarter 1
                            categories:
                              - id: 101
                                name: Classwork
                                sub_categories:
                                  - id: 1001
                                    name: Quiz
                                  - id: 1002
                                    name: Homework
                              - id: 102
                                name: Participation
                                sub_categories: []
                          - id: 12
                            name: Quarter 2
                            categories:
                              - id: 103
                                name: Projects
                                sub_categories:
                                  - id: 1003
                                    name: Final Project
                      - id: 2
                        name: Semester 2
                        categories:
                          - id: 104
                            name: Final Exam
                            sub_categories: []
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../../Data/UnauthorizedError.yaml
        '403':
          description: Access Denied
          content:
            application/json:
              schema:
                $ref: ../../Data/ForbiddenError.yaml
                x-examples:
                  Example 1:
                    error: Access Denied
                    message: Only Admins and SuperAdmins can access grading period data.
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ../../Data/NotFoundError.yaml
                x-examples:
                  Example 1:
                    error: Not Found
                    message: One or more course_ids provided do not exist.
      operationId: get-grading_periods-course_grading_periods_with_categories
      description: |
        Returns all grading periods, sub-grading periods, categories, and sub-categories associated with the provided course IDs.
      parameters:
        - schema:
            type: array
          in: query
          name: course_ids
          required: true
      requestBody:
        content: {}
  /grade_bulks/validate:
    post:
      summary: ''
      operationId: post-grade_bulks-validate
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                x-examples:
                  Example 1:
                    message: Validation successful. All courses and grading periods are valid.
              examples:
                Example 1:
                  value:
                    message: Validation successful.
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../../Data/UnauthorizedError.yaml
        '403':
          description: Access Denied
          content:
            application/json:
              schema:
                $ref: ../../Data/ForbiddenError.yaml
                x-examples:
                  Example 1:
                    error: Access Denied
                    message: Only Admins and SuperAdmins can validate grade bulks.
        '406':
          description: |-
            SK001 → some grading periods/categories not assigned (no corresponding courses sent)

            SK002 → some no grading system assigned

            SK003 → some grading period/sub-period locked

            SK004 → some grading periods/categories does not exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                  error_message:
                    type: string
                x-examples:
                  Example 1:
                    error_code: SK002
                    error_message: Some courses skipped - no grading system assigned.
              examples:
                Example 1:
                  value:
                    error_code: SK001
                    error_message: Some grading periods/categories not assigned (no corresponding courses sent).
                Example 2:
                  value:
                    error_code: SK002
                    error_message: Some courses skipped - no grading system assigned.
                Example 3:
                  value:
                    error_code: SK002
                    error_message: Some courses skipped - no grading system assigned.
                Example 4:
                  value:
                    error_code: SK004
                    error_message: Some grading periods/categories do not exist.
      description: |
        Validate the payload before creating grouped grade items.
        This ensures grading periods, categories, and course data are consistent and assigned correctly.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                Example 1:
                  sections:
                    - section_id: 0
                      stage_id: 0
                      level_id: 0
                      course_id: 0
                      course_group_id: 0
                  grading_periods:
                    - grading_period_id: 0
                      sub_grading_period_id: null
                      category_id: 0
                      sub_category_id: null
                      max_grade: 0
                      default_value: 0
                      hide_grade: false
                      controlled: false
              properties:
                sections:
                  type: array
                  items:
                    type: object
                    properties:
                      section_id:
                        type: integer
                      stage_id:
                        type: integer
                      level_id:
                        type: integer
                      course_id:
                        type: integer
                      course_group_id:
                        type: integer
                    required:
                      - section_id
                      - stage_id
                      - level_id
                      - course_id
                      - course_group_id
                grading_periods:
                  type: array
                  items:
                    type: object
                    properties:
                      grading_period_id:
                        type: integer
                      sub_grading_period_id:
                        type: 'null'
                      category_id:
                        type: integer
                      sub_category_id:
                        type: 'null'
                    required:
                      - grading_period_id
                      - category_id
                max_grade:
                  type: integer
                  x-stoplight:
                    id: qu8f6ac18bgl4
                default_value:
                  type: integer
                  x-stoplight:
                    id: cu6p5dewupwna
                hide_grade:
                  type: boolean
                  x-stoplight:
                    id: b3r2x5b4cm0iv
                controlled:
                  type: boolean
                  x-stoplight:
                    id: 19orjmj3ygvmn
              required:
                - sections
                - grading_periods
                - max_grade
                - default_value
            examples:
              Example 1:
                value:
                  sections:
                    - section_id: 0
                      stage_id: 0
                      level_id: 0
                      course_id: 0
                      course_group_id: 0
                  grading_periods:
                    - grading_period_id: 0
                      sub_grading_period_id: 0
                      category_id: 0
                      sub_category_id: 0
                      max_grade: 0
                      default_value: 0
                      hide_grade: true
                      controlled: true
  /grade_bulks:
    post:
      summary: ''
      operationId: post-grade_bulks
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../../Data/UnauthorizedError.yaml
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: ../../Data/ForbiddenError.yaml
                x-examples:
                  Example 1:
                    error: Access Denied
                    message: Only Admins and SuperAdmins can create grade bulks.
        '406':
          description: |-
            SK001 → some grading periods/categories not assigned (no corresponding courses sent)

            SK002 → some no grading system assigned

            SK003 → some grading period/sub-period locked

            SK004 → some grading periods/categories does not exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                  error_message:
                    type: string
                x-examples:
                  Example 1:
                    error_code: SK003
                    error_message: Some courses skipped - grading period/sub-period locked.
              examples:
                '': {}
                Example 1:
                  value:
                    error_code: SK001
                    error_message: Some grading periods/categories not assigned (no corresponding courses sent).
                Example 2:
                  value:
                    error_code: SK002
                    error_message: Some courses skipped - no grading system assigned.
                Example 3:
                  value:
                    error_code: SK003
                    error_message: Some courses skipped - grading period/sub-period locked.
                Example 4:
                  value:
                    error_code: SK004
                    error_message: Some grading periods/categories do not exist.
      description: |-
        Create a new group of grade items (bulk) after successful validation.
        Only Admins and SuperAdmins are authorized to perform this action.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                Example 1:
                  sections:
                    - section_id: 0
                      stage_id: 0
                      level_id: 0
                      course_id: 0
                      course_group_id: 0
                  grading_periods:
                    - grading_period_id: 0
                      sub_grading_period_id: null
                      category_id: 0
                      sub_category_id: null
                      max_grade: 0
                      default_value: 0
                      hide_grade: false
                      controlled: false
              properties:
                sections:
                  type: array
                  items:
                    type: object
                    properties:
                      section_id:
                        type: integer
                      stage_id:
                        type: integer
                      level_id:
                        type: integer
                      course_id:
                        type: integer
                      course_group_id:
                        type: integer
                    required:
                      - section_id
                      - stage_id
                      - level_id
                      - course_id
                      - course_group_id
                grading_periods:
                  type: array
                  items:
                    type: object
                    properties:
                      grading_period_id:
                        type: integer
                      sub_grading_period_id:
                        type: 'null'
                      category_id:
                        type: integer
                      sub_category_id:
                        type: 'null'
                    required:
                      - grading_period_id
                      - category_id
                max_grade:
                  type: integer
                  x-stoplight:
                    id: c7ot3z389htqf
                default_value:
                  type: integer
                  x-stoplight:
                    id: yp9f3oc1rmyf7
                hide_grade:
                  type: boolean
                  x-stoplight:
                    id: 4ue4sgh2ofpn7
                controlled:
                  type: boolean
                  x-stoplight:
                    id: 9cf6nq68fjbff
              required:
                - sections
                - grading_periods
                - max_grade
                - default_value
            examples:
              Example 1:
                value:
                  sections:
                    - section_id: 1
                      stage_id: 3
                      level_id: 2
                      course_id: 10
                      course_group_id: 58
                    - section_id: 2
                      stage_id: 4
                      level_id: 2
                      course_id: 11
                      course_group_id: 68
                  grading_periods:
                    - grading_period_id: 1
                      sub_grading_period_id: 11
                      category_id: 101
                      sub_category_id: 1001
                      max_grade: 100
                      default_value: 0
                      hide_grade: false
                      controlled: true
                    - grading_period_id: 2
                      sub_grading_period_id: null
                      category_id: 102
                      sub_category_id: null
                      max_grade: 50
                      default_value: 10
                      hide_grade: true
                      controlled: false
  '/courses/{course_id}/course_groups/{course_group_id}/grade_items/{grade_item_id}':
    parameters:
      - schema:
          type: string
        name: course_id
        in: path
        required: true
      - schema:
          type: string
        name: course_group_id
        in: path
        required: true
      - schema:
          type: string
        name: grade_item_id
        in: path
        required: true
    put:
      summary: ''
      operationId: put-courses-course_id-course_groups-course_group_id-grade_items-grade_item_id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    id: 0
                    name: ''
                    max_grade: ''
                    grading_period_id: 0
                    category_id: 0
                    categoryParentId: 0
                    gradingPeriodParentId: 0
                    grading_period:
                      id: 0
                      name: ''
                      start_date: ''
                      end_date: ''
                      parent_name: ''
                      lock: false
                      course_grading_period_lock: false
                      sub_grading_periods_attributes:
                        - id: 0
                          name: ''
                          start_date: ''
                          end_date: ''
                          lock: false
                    category:
                      id: 0
                      name: ''
                      sub_categories_attributes:
                        - id: 0
                          name: ''
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  max_grade:
                    type: string
                  grading_period_id:
                    type: integer
                  category_id:
                    type: integer
                  categoryParentId:
                    type: integer
                  gradingPeriodParentId:
                    type: integer
                  grading_period:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      start_date:
                        type: string
                      end_date:
                        type: string
                      parent_name:
                        type: string
                      lock:
                        type: boolean
                      course_grading_period_lock:
                        type: boolean
                      sub_grading_periods_attributes:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                            name:
                              type: string
                            start_date:
                              type: string
                            end_date:
                              type: string
                            lock:
                              type: boolean
                  category:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      sub_categories_attributes:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                            name:
                              type: string
                required:
                  - id
                  - name
                  - max_grade
                  - grading_period_id
                  - category_id
                  - grading_period
                  - category
              examples:
                Example 1:
                  value:
                    id: 344
                    name: menna3
                    max_grade: '100.0'
                    grading_period_id: 23
                    category_id: 16
                    categoryParentId: 14
                    gradingPeriodParentId: 22
                    grading_period:
                      id: 23
                      name: Quarter 1
                      start_date: '2025-10-03'
                      end_date: '2025-10-10'
                      sub_grading_periods_attributes:
                        - id: 11
                          name: Midterm 1
                          start_date: '2025-09-01'
                          end_date: '2025-09-30'
                          lock: false
                        - id: 12
                          name: Midterm 2
                          start_date: '2025-10-01'
                          end_date: '2025-10-20'
                          lock: false
                      parent_name: Semester 1
                      lock: null
                      course_grading_period_lock: false
                    category:
                      id: 16
                      name: New Sub Category2
                      sub_categories_attributes:
                        - id: 20
                          name: Quiz
                        - id: 21
                          name: Homework
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../../Data/UnauthorizedError.yaml
                x-examples:
                  Example 1:
                    error: Unauthorized
                    message: You need to sign in or sign up before continuing.
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: ../../Data/ForbiddenError.yaml
                x-examples:
                  Example 1:
                    error: Forbidden
                    message: You are not authorized to perform this action.
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      field_name:
                        type: array
                        items:
                          type: string
                x-examples:
                  Example 1:
                    errors:
                      field_name:
                        - error message
        '423':
          description: Locked (WebDAV)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string
                x-examples:
                  Example 1:
                    error: Locked
                    message: The gradebook or grading period is locked.
      description: |
        Updates an existing grade item record.

        New Behavior:
        If the grade item being updated has a `bulk_number` that is **not null**, 
        the system will automatically remove it from its bulk group — 
        i.e., sets `bulk_number = null` to detach it from the bulk creation group.
  '/courses/:course_id/course_groups/:course_group_id/grade_items/:grade_item_id':
    delete:
      summary: ''
      operationId: 'delete-courses-:course_id-course_groups-:course_group_id-grade_items-:grade_item_id'
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../../Data/UnauthorizedError.yaml
                x-examples:
                  Example 1:
                    error: Unauthorized
                    message: You need to sign in or sign up before continuing.
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: ../../Data/ForbiddenError.yaml
                x-examples:
                  Example 1:
                    error: Forbidden
                    message: You are not authorized to delete grade items.
      description: '  '
components:
  schemas: {}
